---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy = TRUE,
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# cmapplot

This R package provides themes and color scales for [`ggplot2`](https://github.com/tidyverse/ggplot2), based on Chicago Metropolitan Agency for Planning (CMAP) design guidelines.

## Installation

Run the following:

```{r eval=FALSE, message=FALSE, warning=FALSE, eval=FALSE}
# install.packages("devtools")
devtools::install_github("CMAP-REPOS/cmapplot")
```

```{r message=FALSE, warning=FALSE, eval=FALSE}
library(cmapplot)
```


# Discrete palettes

```{r include=FALSE}
library(cmapplot)
devtools::load_all()
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_palette(cmap_palettes$environment)
viz_palette(cmap_palettes$governance)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_palette(cmap_palettes$mobility)
viz_palette(cmap_palettes$legislation)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_palette(cmap_palettes$prosperity)
viz_palette(cmap_palettes$community)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_palette(cmap_palettes$friday)
```


# Continuous palettes

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$red_gradient)
viz_gradient(cmap_gradients$orange_red)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$orange_gradient)
viz_gradient(cmap_gradients$yellow_orange)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$yellow_gradient)
viz_gradient(cmap_gradients$yellow_green)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$green_gradient)
viz_gradient(cmap_gradients$green_teal)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$teal_gradient)
viz_gradient(cmap_gradients$teal_blue)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$blue_gradient)
viz_gradient(cmap_gradients$blue_purple)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$purple_gradient)
viz_gradient(cmap_gradients$red_purple)
```

```{r echo=FALSE, out.height="40%", out.width="50%"}
viz_gradient(cmap_gradients$grey_gradient)
```
