---
title: "Installing cmapplot on a CMAP computer"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installing cmapplot on a CMAP computer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette gives an overview of how to install cmapplot onto a CMAP-issued computer.


## Installing necessary components

Your CMAP computer should already have a copy of both R and RStudio installed. If it does not, please contact IT, as they will be able to assist you in installing both (while you should be able to install RStudio on your own, installing R typically requires administrator privileges).

Once you have confirmed that you have a working version of RStudio and R on your computer, you will need to download and install several packages and utilities. One of these can be installed directly through RStudio: `devtools`. You can install it by running the following code:

``` r
## Install devtools 
install.packages("devtools")
```

To build the cmapplot package, you will also need to download a utility called Rtools. You can download the installation file for Rtools [here](https://cran.rstudio.com/bin/windows/Rtools/). Because of administrator restrictions, you will need to choose an installation folder that you have write access to. The installation wizard should default to the top-level "C:" folder, which should work for installation. However, if you do not want to install it there, you may create another folder in your own User sub-directory (note that while "Program Files" is an apparently natural home, installing it there requires administrator privileges).

## Installing and loading cmapplot

Once you have successfully downloaded and installed Rtools, you are ready to install cmapplot. Run the following to install or update cmapplot:

``` r
## Install current version from GitHub
devtools::install_github("CMAP-REPOS/cmapplot", build_vignettes=TRUE)

## Then load the package as you would any other
library(cmapplot)
```

After completing these steps, your computer should be ready to use and export graphics using cmapplot. 

## Fonts

Because your laptop should already have Whitney installed, your graphics should be outputted using the Whitney font families. If, however, you receive an error message warning you that Whitney is not installed, please verify that Whitney is installed on your device. If it is not, please contact IT to ask for their help in getting the font added to your machine. If Whitney is installed, but you are still receiving the warning message, please reach out to a member of the cmapplot development team.
